# Generated by Django 3.1.2 on 2020-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200917_0721"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop", name="status", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="delivery_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
