# Generated by Django 3.1 on 2020-08-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_productinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductParameter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.parameter"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="category", name="shops",),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(default="11", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price_rrc",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.shop"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(name="ProductInfo",),
        migrations.AddField(
            model_name="productparameter",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parameters",
            field=models.ManyToManyField(
                through="api.ProductParameter", to="api.Parameter"
            ),
        ),
    ]
