# Generated by Django 3.1 on 2020-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200818_0551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=100),
        ),
    ]
